desc: Python-Template

#-------------------------------------------------------------------------------
# バージョン
#-------------------------------------------------------------------------------
VERSION: "V1.0.0"

#-------------------------------------------------------------------------------
# Log
#-------------------------------------------------------------------------------
# ログ出力先フォルダパス
LOG_FOLDER: log
# ログメッセージファイルパス
LOG_MSG_FILE: message.yml
